# Generated by Django 3.2.9 on 2021-11-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211121_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_owner',
        ),
    ]
